# Generated by Django 3.1.3 on 2021-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
