# Generated by Django 3.1 on 2020-12-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='token',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
