# Generated by Django 3.1.3 on 2021-01-31 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twits',
            name='cleaned_text',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='twits',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twits',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twits',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_result', models.CharField(blank=True, max_length=100, null=True)),
                ('graph_img', models.BinaryField(blank=True, editable=True, null=True)),
                ('wordcloud_img', models.BinaryField(blank=True, editable=True, null=True)),
                ('twits', models.ManyToManyField(blank=True, related_name='results', to='posts.Twits')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
